Optimize (little bit) view score.py
uclouvain/osis-internship pull request #174
Opened 2020-06-08 19:29 UTC by BenJneB

2020-06-08 22:21 UTC, BenJneB commented
Idéalement, remonter à la source de chaque queryset que j'aurais oublié et y faire les select/prefetch adéquat.

2020-11-27 14:25 UTC, BenJneB commented on views/affectation.py
> -    specialty = models.internship_speciality.get_by_id(filter_specialty)
ej n'ai aucune idée de pourquoi j'ai retiré ca

2020-11-27 14:32 UTC, mathieuzen requested changes

2020-11-27 14:32 UTC, mathieuzen commented on business/assignment.py
> +                choice.choice = ChoiceType.IMPOSED.value
peut-être diviser pour mieux lire la condition du premier if dans "is_non_mandatory_internship_not_first_choice"

2020-11-27 14:32 UTC, mathieuzen commented on models/period.py
> +        return self.date_start <= date.today() <= self.date_end
je savais pas qu'on pouvait faire ça en python :-)

2020-11-27 14:34 UTC, mathieuzen commented on views/affectation.py
> -    specialty = models.internship_speciality.get_by_id(filter_specialty)
probablement pas utilisé

2020-11-27 14:36 UTC, BenJneB commented on models/period.py
> +        return self.date_start <= date.today() <= self.date_end
Python interval comparison

2020-11-27 14:39 UTC, BenJneB commented on views/affectation.py
> -    specialty = models.internship_speciality.get_by_id(filter_specialty)
ben j'ai l'impresssion que si ! a check

2020-11-27 14:48 UTC, mathieuzen commented on views/affectation.py
> -    specialty = models.internship_speciality.get_by_id(filter_specialty)
c'est pour garder la spécialité active dans le dropdown quand on change d'organisation dans 'allocation_sum_up'

2020-11-27 14:48 UTC, mathieuzen commented on views/affectation.py
> -    specialty = models.internship_speciality.get_by_id(filter_specialty)
mieux vaut le remettre

2021-01-04 09:33 UTC, mathieuzen approved these changes

2021-01-04 14:42 UTC, merged