INTERNSHIP-210 init API with InternshipMaster
uclouvain/osis-internship pull request #182
Opened 2020-11-23 15:57 UTC by mathieuzen

2020-11-27 11:45 UTC, BenJneB commented on api/serializers/internship_master.py
> +            'email'
tu comptais pas lier à Person ?

2020-11-27 11:48 UTC, mathieuzen commented on api/serializers/internship_master.py
> +            'email'
si mais je voulais un truc qui fonctionne d'abord, le lien avec Person c'est pour un autre ticket

2020-11-27 11:55 UTC, BenJneB requested changes

2020-11-27 11:55 UTC, BenJneB commented on api/serializers/internship_student_information.py
> +            'phone_mobile',
On pourrait réfléchir à voir si on peut lier à StudentAddress ?

2020-11-27 11:55 UTC, BenJneB commented on api/views/cohort.py
> +    def get_serializer_class(self):
si t'as qu'un serializer
pas besoin de la méthode, tu peux directement faire serializer_class =

2020-11-27 11:55 UTC, BenJneB commented on schema.yml
> +          type: date
ce type n'existe pas !

2020-11-27 11:55 UTC, BenJneB commented on schema.yml
> +        master:
Ce n'est pas un string mais un autre serializer donc un object !

2020-11-27 11:55 UTC, BenJneB commented on schema.yml
> +        master:
Idem pour organization & Specialty

2020-11-27 11:55 UTC, BenJneB commented on schema.yml
> +        cohort:
Idem

2020-11-27 11:55 UTC, BenJneB commented on schema.yml
> +        cohort:
idem

2020-11-27 11:55 UTC, BenJneB commented on schema.yml
> +        country:
idem

2020-11-27 11:55 UTC, BenJneB commented on schema.yml
> +          example: "R6-2021"
idem

2020-11-27 11:55 UTC, BenJneB commented on schema.yml
> +        person:
idem

2020-11-27 11:55 UTC, BenJneB commented on schema.yml
> +        cohort:
idem

2020-11-27 11:55 UTC, BenJneB commented on schema.yml
> +          example: "XYZ"
idem

2020-11-30 08:35 UTC, lspitaels commented on api/url_v1.py
> +]
je préfixerais les url avec "api/"
vous en pensez quoi?

2020-11-30 08:57 UTC, BenJneB commented on api/url_v1.py
> +]
ca le sera via l'import dans webservices

2020-11-30 09:01 UTC, BenJneB requested changes

2020-11-30 09:01 UTC, BenJneB commented on schema.yml
> -          type: string
Regarde comment on référence un objet existant dans les autres schéma :)

comme pour l'uuid...

2020-11-30 09:01 UTC, BenJneB commented on schema.yml
> +          type: number
Ca peux être autre chose qu'un entier ?

2020-11-30 09:01 UTC, BenJneB commented on schema.yml
> +          type: string
c'est pas un string !!!

2020-11-30 09:01 UTC, BenJneB commented
Pense à passer ton schema dans swagger editor pour vérifier le format

2020-11-30 10:13 UTC, mathieuzen commented on schema.yml
> +          type: number
nope

2020-11-30 10:13 UTC, mathieuzen commented on schema.yml
> +          type: string
ici oui :-D

2020-11-30 10:32 UTC, BenJneB commented on schema.yml
> +          type: number
Alors pourquoi changer en number?

2020-11-30 13:33 UTC, mathieuzen commented on schema.yml
> +          type: number
integer est pas repris je pense dans les spécifications du schéma

2020-11-30 13:34 UTC, mathieuzen commented on schema.yml
> +          type: number
ah ben si zut :-)

2020-12-01 10:13 UTC, BenJneB approved these changes

2020-12-01 10:16 UTC, merged