INTERNSHIP-208 clean masters duplicates and link data to base.Person
uclouvain/osis-internship pull request #183
Opened 2020-12-01 12:33 UTC by mathieuzen

2020-12-01 15:16 UTC, BenJneB requested changes

2020-12-01 15:16 UTC, BenJneB commented on templates/master.html
> -        <h2>
tu as retiré un truc là ! :D

2020-12-01 15:16 UTC, BenJneB commented
Tester PersonForm

2020-12-01 15:29 UTC, lspitaels commented on forms/Internship_person_form.py
> +#    Copyright (C) 2015-2019 Université catholique de Louvain (http://www.uclouvain.be)
on est en 2020 ;) bientôt 2021 même

2020-12-02 09:30 UTC, mathieuzen commented on forms/Internship_person_form.py
> +#    Copyright (C) 2015-2019 Université catholique de Louvain (http://www.uclouvain.be)
je la voyais venir celle là :-)

2020-12-02 09:31 UTC, mathieuzen commented on forms/Internship_person_form.py
> +#    Copyright (C) 2015-2019 Université catholique de Louvain (http://www.uclouvain.be)
mais par contre tu m'as fait remarqué en plus que mon nom de fichier commençait par une majuscule... et ça c'est beau ! :-D

2020-12-04 11:35 UTC, BenJneB approved these changes

2020-12-04 13:51 UTC, merged