INTERNSHIP-208 consider source while creating person linked to master
uclouvain/osis-internship pull request #186
Opened 2020-12-14 14:02 UTC by mathieuzen

2020-12-14 14:10 UTC, lspitaels approved these changes

2020-12-15 09:02 UTC, BenJneB requested changes

2020-12-15 09:02 UTC, BenJneB commented on migrations/0093_internshipmaster_person.py
> +                source='Internship'
utilise l'enum

2020-12-15 09:35 UTC, BenJneB approved these changes

2020-12-15 09:37 UTC, merged