INTERNSHIP-207 create internship master user account
uclouvain/osis-internship pull request #189
Opened 2021-01-06 13:37 UTC by mathieuzen

2021-01-06 14:06 UTC, BenJneB approved these changes

2021-01-06 14:30 UTC, BenJneB approved these changes

2021-01-07 10:38 UTC, BenJneB requested changes

2021-01-07 10:38 UTC, BenJneB commented on models/enums/user_account_status.py
> +    ACTIVE = "active"
Tu veux pas les avoir traduit?

2021-01-08 14:38 UTC, mathieuzen commented on models/enums/user_account_status.py
> +    ACTIVE = "active"
non pas vraiment utile

2021-01-08 14:45 UTC, BenJneB approved these changes

2021-01-08 15:19 UTC, merged