INTERNSHIP-198 adapt api service for score_encoding to serve affectat…
uclouvain/osis-internship pull request #191
Opened 2021-01-15 16:28 UTC by mathieuzen

…ions

2021-01-25 10:57 UTC, BenJneB requested changes

2021-01-25 10:57 UTC, BenJneB commented on api/url_v1.py
> +    url(r'^periods/active$', PeriodActiveList.as_view(), name=PeriodActiveList.name),
j'ajouterais plutot un Filtre!

2021-01-25 10:57 UTC, BenJneB commented on api/views/internship_student_affectation_stat.py
> +        # TODO: use another way to retrieve student affectations in order to not retrieve all objects without params
Pas bien saisi?

2021-01-25 10:57 UTC, BenJneB commented on api/views/internship_student_affectation_stat.py
> +        specialty_uuid = self.request.query_params.get('specialty')
Ils sont pas dans self.kwargs??

2021-01-25 10:57 UTC, BenJneB commented on api/views/period.py
> +
doublon non?

2021-01-25 11:08 UTC, BenJneB commented on api/url_v1.py
> +    url(r'^periods/active$', PeriodActiveList.as_view(), name=PeriodActiveList.name),
?active=true

2021-01-25 15:15 UTC, mathieuzen commented on api/views/internship_student_affectation_stat.py
> +        # TODO: use another way to retrieve student affectations in order to not retrieve all objects without params
enfait comme c'est là, je peux récupérer toutes les affectations sans mettre de paramètres donc faut que je change ça

2021-01-25 15:16 UTC, mathieuzen commented on api/views/internship_student_affectation_stat.py
> +        specialty_uuid = self.request.query_params.get('specialty')
non je sais plus pourquoi j'ai mis ça dans les query params

2021-01-27 09:17 UTC, BenJneB approved these changes

2021-01-27 13:18 UTC, merged