INTERNSHIP-217 use LDAP user account creation for master
uclouvain/osis-internship pull request #192
Opened 2021-01-27 15:17 UTC by mathieuzen

2021-01-27 15:24 UTC, BenJneB requested changes

2021-01-27 15:24 UTC, BenJneB commented on views/master.py
> +        url="https://gildap.sipr.ucl.ac.be/osis/createUser/"
tu devrais pas mettre l'url ailleurs? voir le .env? a demander à d'autres ?

2021-01-27 15:25 UTC, BenJneB commented on views/master.py
> +        url="https://gildap.sipr.ucl.ac.be/osis/createUser/"
De plus, t'es sur de vouloir appeler ca sur tout les environnements???

2021-01-28 08:27 UTC, mathieuzen commented on views/master.py
> +        url="https://gildap.sipr.ucl.ac.be/osis/createUser/"
Oui c'est direct en prod mais t'as raison je vais le mettre dans le .env

2021-01-28 10:19 UTC, BenJneB commented on views/master.py
> +        url="https://gildap.sipr.ucl.ac.be/osis/createUser/"
mais c'est pas un soucis que ca appelle cette url sur DEV et autres?

2021-01-28 13:36 UTC, BenJneB approved these changes

2021-01-28 13:49 UTC, merged