INTERNSHIP-197 celery cron task to send reminder before active period end
uclouvain/osis-internship pull request #199
Opened 2021-02-12 14:53 UTC by mathieuzen

2021-02-12 15:08 UTC, lspitaels requested changes
N'oublie pas les trad ;)

2021-02-12 15:08 UTC, lspitaels commented on tasks/__init__.py
> +        'schedule': crontab(minute=0, hour=0)
c'est un détail mais je mettrais à 8h (début de journée) plutôt que pendant la nuit

2021-02-12 15:08 UTC, lspitaels commented on utils/mails/mails_management.py
> +    organizations = [i.organization_id for i in effective_internships]
tu pourrais faire ça en une boucle

2021-02-12 15:08 UTC, lspitaels commented on models/period.py
> +    sent_reminder_mail = models.BooleanField(default=False)
c'est un détail mais 'sent' ici est un participe passé donc ça serait mieux d'appeler la variable 'reminder_mail_sent'

2021-02-12 15:16 UTC, mathieuzen commented on migrations/0099_period_sent_reminder_mail.py
> +# Generated by Django 3.1.1 on 2021-02-12 11:41
jamais fait gaffe jusqu'ici je pense je suis en django 3 en local depuis longtemps donc il y a probablement déjà plusieurs migrations comme ça

2021-02-12 15:16 UTC, mathieuzen commented on tasks/__init__.py
> +        'schedule': crontab(minute=0, hour=0)
ok je change ça

2021-02-12 15:16 UTC, mathieuzen commented on utils/mails/mails_management.py
> +    organizations = [i.organization_id for i in effective_internships]
oui j'y ai pensé justement, je voulais en effet optimiser un peu ceci

2021-02-12 15:17 UTC, mathieuzen commented on models/period.py
> +    sent_reminder_mail = models.BooleanField(default=False)
ok

2021-02-22 09:19 UTC, mathieuzen commented on migrations/0099_period_sent_reminder_mail.py
> +# Generated by Django 3.1.1 on 2021-02-12 11:41
en fait toutes les migrations internship :-D

2021-02-22 12:14 UTC, lspitaels commented on utils/mails/mails_management.py
> +    specialties, organizations = zip(*[(i.speciality_id, i.organization_id) for i in effective_internships])
ça c'est beau

2021-02-22 12:14 UTC, lspitaels approved these changes

2021-02-22 12:53 UTC, merged